# Use postgres/example user/password credentials
version: '3.1'

services:

  pgserver:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: umasenha
      POSTGRES_USER: admin
      POSTGRES_DB: pg_cocierge

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080